name: Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: "make all"
        uses: ./.github/actions/builder
        with:
          entrypoint: /usr/bin/make
          args: all

      - name: "hack - workaround github actions runner filesystem permission issue"
        # This hack should not be necessary, but if we don't do it, the
        # next step fails during docker build as docker does not have
        # permission to read files included in the github workspace that
        # were written by the previous step. This is pretty daft as we
        # don't even want or need docker to attempt to read these files
        # during the image build. Github actions appears to give us no way
        # to customise the build context to exclude it trying to read these
        # files.
        #
        # Refs:
        # https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user
        # https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#filesystems-on-github-hosted-runners
        # https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: "make auto-test"
        uses: ./.github/actions/builder
        with:
          entrypoint: /usr/bin/make
          args: auto-test

      - name: "make check-tidy"
        uses: ./.github/actions/builder
        with:
          entrypoint: /usr/bin/make
          args: check-tidy

  downstream_test:
    name: Test against downstream repos
    runs-on: ubuntu-latest
    container: golang:1.16-stretch
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Test against downstream repos
        env:
          DOWNSTREAM_TEST: ${{ secrets.DOWNSTREAM_TEST }}
          ORG_GITHUB_TOKEN: ${{ secrets.SYSL_REGRESSION_TEST_TOKEN }}
        run: eval "${DOWNSTREAM_TEST:-echo 'no downstream repos to test'}"
